@ManageProperties.API_HostAddress = https://localhost:7296/api/owners

GET {{ManageProperties.API_HostAddress}}/0199162E-8E7E-7DBA-8DEF-CCE2A1C11A73  
Accept: application/json

###

GET {{ManageProperties.API_HostAddress}}   
Accept: application/json
Authorization : Bearer CfDJ8PsimWycmItNsI-2_pyzgnlb8zG_mb_XSpxNk22vBQpoK9SXL0kKpRVqOzIa01Q2S6edNp6y8HfbNds20Pu1FhcRhTPOi-mIAbzJ_MZTPg1ciEItGkKenZBZH495HWWGzbrOResGnar8tiITLkPDgYIbbzhIUXcZvXJ5-Til3ecRMDXuDeC5vZwiJFZnXInd0SvF4UbGhgXzTg8gF1AfExaWoHMfEyXbNDLEn_pHrq8aSMXVfz59NL4ZipwOnHlVZWxUeB-H0Kj1wnieeBvtx-Jg_TIE4G_iMoNKKntOqVej7V_PgfGrfttQDZKi23SuNuBU7bl25gQugJS9iF5ZBMcSfhVWzdfIssFOy25HnNQcPZnIms5VV4jh8W9fY5BSxnkLJu4Z_BQtGgjchTUIc63TnTczG0ORWckPS-1jgjo4fU_QcvfL7pNoazseSkrlSVS4Zvy0EeE8T-GzWw5FdCMVkuTBVVjMkhQVSNb_sjd36CerOpY5jcaL0OFMvSzdj-OyyDBStoDzSjbppRk21ZekzweSoUl0Q_EHhqR7o1_bblRc-u4KIfHSaddr-Ze9SuTQOqM4HvuyBsgHqz2_uoapU14uM_EhYw9WL3B19iEeD2keY0-431N0e8agnipPpWc_QYx-Qlg32_zHz3WkOkNpLFQyOWUhApTtISZG2IqvtQN8HYgks0ZG-Eo5rBOoX9G43r_yEltTbLui1qDhAxqY9RVI9ITfRUQ0pkx_t8GTjKKKWlI8zieT-Kjvi-jHNQ


###

POST {{ManageProperties.API_HostAddress}}
Content-Type: application/json

{
  "Name": "Owner three",
  "Address": "Calle 123  av 567",
  "Photo": "string.png",
  "Birthday": "1977-06-20"
}

###

PUT {{ManageProperties.API_HostAddress}}/01991645-DA12-7885-861B-002C14682273
Content-Type: application/json

{
  "Name": "Owner one Updated two",
  "Address": "string",
  "Photo": "string.new",
  "Birthday": "1994-06-20"
}

###

DELETE {{ManageProperties.API_HostAddress}}/01991645-DA12-7885-861B-002C14682273
Accept: application/json