@ManageProperties.API_HostAddress = https://localhost:7296/api/owners

GET {{ManageProperties.API_HostAddress}}/0199162E-8E7E-7DBA-8DEF-CCE2A1C11A73  
Accept: application/json

###

GET {{ManageProperties.API_HostAddress}}   
Accept: application/json
Authorization : Bearer CfDJ8PsimWycmItNsI-2_pyzgnnl6R4ksWEL56T5kD9fi9CdR8vWb2B_ub_ORYNkchc5Wp4GvFQ0onF2IY9tW_kk-5MOuqehfMKzaFNfdqkiHQ7Dt15K6XHokb1DWTYBq5bTle1zGaHatxzcsetyHLrIIRX2n3TV5nZOlHD4XsQDl1MTAAM4Ucjabp8J51dbTiQBe0iO9H3c0_dDR3ovCOs0WJ5gh5zCUhpbfnBHDGfa1kABZciZkZCT8TPE6qRMM3L8wXHma3QNPQc53heVjOWrjz9TBw80RNFETlTzReCe44ps_eruW2IyHu_jcouJUCpDlQuGYmFkMLi_c8s4HuB7LM8-Acowcpu1zkebnzfjNwz-BRXVvWjIll1gVqZSoBvZa5vUUwQIK_U7NeYoLcCMYAZ-BfGAF_4vFJnQqKWL5q3y8zv8EWJnqbc-r5fgJ3wkzXYiEuW2RMQkYbOOuSVPvSoCaYk-4g2uNj5ad8rnnzC-PqJ8OWPe8tzsN2xtz7KLtejOCDrdwJn8HrWlDUTMjoDRcBdKBknYBz_lF7ojODKzl8NCVAH3gx9764qfHO27lAYa9Dasdnr1A4IXxE0za4O1u6HjrmAHZBl0hCoVk35NWC3lJewK1kSHGLCjbkycE_ihfEkmeiswVrLfKdS780V5G8mJCxmYbM8ujZo5gOc8euHur-9P6xbRl9AWpNOMryyXcUF30ISf0ihdA61qIU3oqupcbHgGWq4KDStfpsvTdi8bMSA19oa6F97cmeJTyw

###

POST {{ManageProperties.API_HostAddress}}
Content-Type: application/json

{
  "Name": "Owner three",
  "Address": "Calle 123  av 567",
  "Photo": "string.png",
  "Birthday": "1977-06-20"
}

###

PUT {{ManageProperties.API_HostAddress}}/01991645-DA12-7885-861B-002C14682273
Content-Type: application/json

{
  "Name": "Owner one Updated two",
  "Address": "string",
  "Photo": "string.new",
  "Birthday": "1994-06-20"
}

###

DELETE {{ManageProperties.API_HostAddress}}/01991645-DA12-7885-861B-002C14682273
Accept: application/json