@ManageProperties.API_HostAddress = http://localhost:5080/api/propertyimage

GET {{ManageProperties.API_HostAddress}}/019924c1-536b-7ec1-a62d-30ccfa4a85f4  
Accept: application/json

###

GET {{ManageProperties.API_HostAddress}}   
Accept: application/json

###

POST {{ManageProperties.API_HostAddress}}
Content-Type: application/json

{
    "PropertyId": "01991828-7b40-76d2-b9d2-bb54a52f1c69",
    "Image": "image_02.png",
    "Enable": "1"
}

###

PUT {{ManageProperties.API_HostAddress}}/01991aad-328e-7956-ad6c-1ef10a8bdbfe
Content-Type: application/json

{
    "PropertyId": "01991793-84d6-7243-ac70-7e89a86f24cf",
    "Image": "image_002.png",
    "Enable": "0"
}

###

DELETE {{ManageProperties.API_HostAddress}}/01991aad-328e-7956-ad6c-1ef10a8bdbfe
Accept: application/json