@ManageProperties.API_HostAddress = https://localhost:7296/api/propertytrace

GET {{ManageProperties.API_HostAddress}}/01991c6c-1880-783b-8a0a-3c31dbc7c7fa  
Accept: application/json

###

GET {{ManageProperties.API_HostAddress}}   
Accept: application/json
Authorization : Bearer CfDJ8PsimWycmItNsI-2_pyzgnmiERUG2CzxW-F8RxYOvOr_N0A-RL93s1piMbr52kwnWPg6LjETVA-3kbGF34DM8SNIxWsbq7Lmi5I-e4nTsfGeSjHtJRlcF-E7uUGjfQ_bk5YtK44x2GrUbZDAN59MB6p70C8-rjSLFWXfwVd1wfSRR0jAFmTexLDYzakWifqFDvwp7tstIcP7R-JHB7_zTWg4OmAuR1gFcxoQYwBGl1sewnmr04yEYdYw6G3o2cqT6T9i-XzzwI4ZvfNkc_jvwEevBUK4GCYQzIIXIAgIZ4mHJGnfth1LjaYy5IrikURDYst8jqrP4u_35hkvj2Rv9_QB6mUUpRGs0WVq1QJM9CI8U_a1EFy4YWu442QPz5hpF5qlnqt_N5T09BXQpA-HgyrADs-ETzFZAe5x1jCJMC0NV_CNkcxld1Dl30A8ym6F_i4kQJk_P3oW5m61wiO4K05f9vnYtcMZlprdFUgnCVY1mNfYNQ1f41Chd4nuYcCxLawv6JThHdiMwhsW9POczPetYnFfNqTaoevEEMaYJwbU0_kNd1tHdxb-aI0b4xP9D6OwXcbo3meudZLAPFqP1t4FZsOyXZkUbpHiBJU60kAPCa8qlvvQGHPADZglqvqVhssJgQov8_D56WW6xXRoOar924IZZoj2ycAcKlbDcIQgil6lRYOfHTR7SncAGAlS9ryv-d1Ri6UN2I0bYN5iMxgdDodrNjir3jTKedLoxd4FpyDiRN22U_Of22JBy7AQ4A
###

POST {{ManageProperties.API_HostAddress}}
Content-Type: application/json

{
    "PropertyId": "01991828-7b40-76d2-b9d2-bb54a52f1c69",
    "DateSale" : "2025-06-21",
    "Name" : "Property trace tres nuevo",
    "Value" : 1000,
    "Tax" : 0.19
}

###

PUT {{ManageProperties.API_HostAddress}}/01991c6c-1880-783b-8a0a-3c31dbc7c7fa
Content-Type: application/json

{
    "PropertyId": "01991828-7b40-76d2-b9d2-bb54a52f1c69",
    "DateSale" : "2025-06-21",
    "Name" : "Property trace tres - Update 2",
    "Value" : 10000,
    "Tax" : 0.21
}

###

DELETE {{ManageProperties.API_HostAddress}}/01991c7b-9c28-7409-93a7-a015fe5a1f89
Accept: application/json